packages:
  - apps/*
  - packages/*

engineStrict: true
saveExact: true
strictPeerDependencies: true
autoInstallPeers: false
preferWorkspacePackages: true
linkWorkspacePackages: true
sharedWorkspaceLockfile: true
nodeLinker: hoisted
confirmModulesPurge: false

overrides:
  '@electron/rebuild': 4.0.4

allowBuilds:
  better-sqlite3: true
  electron: true
  esbuild: true
