import type { TrainingSegmentDefinition } from '@passwo/contracts';

export { SUPPORTIVE_ARTIFACT_VERSION } from '@passwo/contracts';

export const trainingSegments = [
  {
    id: 'S00',
    title: 'Entry and safety boundary',
    section: 'passwords',
    sourcePages: '2',
    foci: ['TF1', 'TF2', 'TF6'],
    learningObjective: 'Fiktive Übungsgrenze, unterstützende Rolle und Aufgabe verstehen.',
  },
  {
    id: 'S01',
    title: 'Ordinary account setup',
    section: 'passwords',
    sourcePages: '3',
    foci: ['TF2', 'TF3'],
    learningObjective: 'Drei selbst erzeugte fiktive Passwortentscheidungen treffen.',
  },
  {
    id: 'S02',
    title: 'Konten kennenlernen',
    section: 'passwords',
    sourcePages: '4-7',
    foci: ['TF2', 'TF3', 'TF4'],
    learningObjective: 'Verbundene Dienste, Kontovorgänge und Kommunikationsbereiche erkunden.',
  },
  {
    id: 'S03',
    title: 'Wieder anmelden',
    section: 'passwords',
    sourcePages: '8-11',
    foci: ['TF1', 'TF3', 'TF6'],
    learningObjective: 'Praktische Abrufbarkeit ohne beschämendes Feedback prüfen.',
  },
  {
    id: 'S04',
    title: 'Datenleck bei Campusgram',
    section: 'passwords',
    sourcePages: '12',
    foci: ['TF4'],
    learningObjective: 'Das Datenleck als Ausgangspunkt für die Angreiferperspektive einordnen.',
  },
  {
    id: 'S05',
    title: 'Einzelstärke des Passworts',
    section: 'passwords',
    sourcePages: '12-35',
    foci: ['TF3', 'TF4', 'TF6'],
    learningObjective: 'Bestandteile, Aufbau und freies Ausprobieren gemeinsam einordnen.',
  },
  {
    id: 'S06',
    title: 'Einzigartigkeit und Ausbreitung',
    section: 'passwords',
    sourcePages: '36-44',
    foci: ['TF3', 'TF4'],
    learningObjective:
      'Exakte Wiederverwendung, konkret abgeleitete Varianten und nicht erkannte Wege unterscheiden.',
  },
  {
    id: 'S07',
    title: 'Auswertung',
    section: 'passwords',
    sourcePages: '44-50',
    foci: ['TF1', 'TF4', 'TF6'],
    learningObjective: 'Pro Konto einen priorisierten nächsten Schritt ableiten.',
  },
  {
    id: 'S08',
    title: 'Passwörter überarbeiten',
    section: 'passwords',
    sourcePages: '50-53',
    foci: ['TF3', 'TF5', 'TF6'],
    learningObjective: 'Sechs unabhängig zufällig erzeugte Wörter anwenden.',
  },
  {
    id: 'S09',
    title: 'Von drei zu vielen Konten',
    section: 'passwords',
    sourcePages: '53-55',
    foci: ['TF4', 'TF5'],
    learningObjective:
      'Stärke, Einzigartigkeit und Abrufbarkeit zusammenführen und das Erinnerungsproblem vieler Konten erkennen.',
  },
  {
    id: 'S10',
    title: 'Zusammenfassung Passwort',
    section: 'passwords',
    sourcePages: '55-57',
    foci: ['TF6'],
    learningObjective: 'Stärke, Einzigartigkeit und Abrufbarkeit trennen.',
  },
  {
    id: 'S11',
    title: 'Von drei zu vielen Konten',
    section: 'passwords',
    sourcePages: '57-60',
    foci: ['TF1', 'TF2', 'TF4', 'TF6'],
    learningObjective: 'Skalierungsproblem menschlicher Erinnerung erkennen.',
  },
  {
    id: 'S12',
    title: 'Passwortmanager',
    section: 'password-manager',
    sourcePages: '60-65',
    foci: ['TF2', 'TF3', 'TF4', 'TF6'],
    learningObjective: 'Erzeugen, Speichern, Ausfüllen und Recovery einordnen.',
  },
  {
    id: 'S13',
    title: 'Ein neues und ein bestehendes Konto',
    section: 'password-manager',
    sourcePages: '65-66',
    foci: ['TF2', 'TF3'],
    learningObjective:
      'Neue Zugangsdaten mit einem Passwortmanager anwenden und die Dienstgrenze bei importierten Zugangsdaten erkennen.',
  },
  {
    id: 'S14',
    title: 'Mehrere Faktoren',
    section: 'mfa',
    sourcePages: '66-67',
    foci: ['TF2', 'TF3', 'TF6'],
    learningObjective: 'Wissen, Besitz und Inhärenz unterscheiden und MFA aktivieren.',
  },
  {
    id: 'S15',
    title: 'Recovery-Hinweis',
    section: 'mfa',
    sourcePages: '67-68',
    foci: ['TF6'],
    learningObjective: 'Geschützte Wiederherstellungsoption als Dienstgrenze verstehen.',
  },
  {
    id: 'S16',
    title: 'Priorisierung und Ausweitung',
    section: 'mfa',
    sourcePages: '68',
    foci: ['TF1', 'TF6'],
    learningObjective: 'Mit weitreichenden Konten beginnen und MFA ausweiten.',
  },
  {
    id: 'S17',
    title: 'Integrierte Zusammenfassung',
    section: 'mfa',
    sourcePages: '69-71',
    foci: ['TF4', 'TF6'],
    learningObjective: 'Vier Schutzebenen und ihre Grenzen zusammenführen.',
  },
] as const satisfies readonly TrainingSegmentDefinition[];
